---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app
  namespace: flux-system
spec:
  interval: 15m0s
  path: ./kustomize
  prune: true
  sourceRef:
    kind: GitRepository
    name: app
  targetNamespace: default

  patches:
    - patch: |-
        apiVersion: autoscaling/v2
        kind: HorizontalPodAutoscaler
        metadata:
          name: app
        spec:
          minReplicas: 2            
          maxReplicas: 3   
      target:
        name: app
        kind: HorizontalPodAutoscaler

