---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: app
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: master 
  url: https://github.com/stefanprodan/podinfo 
